WORKER_PROCESS_SPAWN_TIME = 2
WORKER_PROCESS_TERMINATE_TIME = 2
WORKER_PROCESS_RESTART_TIME = WORKER_PROCESS_SPAWN_TIME + WORKER_PROCESS_TERMINATE_TIME + 2
WORKER_POOL_SPAWN_TIME = 5
KAFKA_WAIT_TIME = 3
