from config import ini_config

WORKER_PROCESS_SPAWN_TIME = 3
WORKER_PROCESS_TERMINATE_TIME = 3
WORKER_PROCESS_RESTART_TIME = WORKER_PROCESS_SPAWN_TIME + WORKER_PROCESS_TERMINATE_TIME + 2
WORKER_POOL_SPAWN_TIME = int(ini_config['worker']['workers']) * WORKER_PROCESS_SPAWN_TIME / 2
KAFKA_WAIT_TIME = 3
